### ISSUE TITLE
bochs doesn't recognize alignment

### ISSUE THREAD

**Issue by qrzbl** [qrzbl/kernel32#12]
When I align `user_ints_tbl` (commit 8ed9b91608837f490dccb82964b33c0a36fb5bf0) to word boundaries with the `.balign` directive like this:

```
SEC_RW_DATA(`.bootsys_data')
.balign 2
user_ints_tbl:
.word vga_entry

.balign 1
.set num_user_ints, (. - user_ints_tbl) / 0x2
```

`objdump -d boot.out -mi8086` notices that and prints

```
00000120 <user_ints_tbl>:
 120:   fb                      sti
```

but somehow bochs doesn't and loads it to `0x8011f`.

If I remove the `.balign` directives, `objdump -d boot.out -mi8086` shows

```
    0000011f <user_ints_tbl>:
 11f:   fb                      sti
```

and bochs still loads it to `0x8011f`. It works fine.

That means, bochs somehow doesn't recognize that alignment. So whose fault is it? bochs', `objdump`'s, or the linker's? And how to solve it?

**Comment by mpetch** [comment]
In the `boot.ld` linker script _SIZEOF_ doesn't account for section alignment. By using _AT_ this way:

    .bootsys_data : AT(LOADADDR(.bootsys_text) + SIZEOF(.bootsys_text)) {

This will likely cause a mismatch between the LMA (load memory address) and the VMA (Virtual memory address). You can probably tell if that is true by using the `-x` parameter with _OBJDUMP_:

    objdump -x boot.out

I'd recommend simplifying `boot.ld` to have _LD_ do most of the computational(address) work for you. This example also combines all the *bootsys_\** into one section.  You could still keep them separate if you choose.

```
ENTRY(boot_start)

SECTIONS {
    . = BOOT_ORG;
    .text : { *(.text) }
    .data : { *(.data) }
    .boot_sig : AT(BOOT_ORG + BOOT_LEN - 0x2) {
        SHORT(0xaa55);
    }

    . = 0;
    .bootsys : AT(BOOT_ORG + BOOT_LEN) {
        *(.bootsys_text)
        *(.bootsys_data)
        *(.bootsys_bss)
    }
}
```

**Comment by qrzbl** [comment]
@mpetch The only reason I use the `MEMORY` command is because this way, ld will raise an error if a segment gets too large. For example, the boot system must not be larger than 64 KiB, it must fit into one Real Mode segment. `MEMORY` seems like the perfect way to achieve that.

**Comment by qrzbl** [comment]
@mpetch I ran some tests and indeed, the load address of `tmp_gdtr` was off by some bytes. I applied your suggestion and that fixed it, thanks. In fact, I had a TODO comment whether to remove this `AT(...) + SIZEOF(...)` construction, but because it seemed redundant to me. I didn't think it would cause alignment problems.
